import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import {Providers} from './Providers';
import classNames from 'classnames';
import Header from '@/components/Common/Header';
import Sidebar from '@/components/Common/Sidebar';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>
          <div
            className='w-full 
                     h-screen 
                     bg-background-main'>
            <Header />
            {/* <Sidebar /> */}
            <main
              className='bg-background-main
                 px-6
                          grid 
                          h-[calc(100%-56px)] 
                          overflow-y-hidden'>
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
